[project]
name = "nkdatabase"
version = "1.0.2"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "build>=1.2.2.post1",
    "pydantic>=2.11.5",
    "ruff>=0.12.10",
    "setuptools>=75.8.0",
    "wheel>=0.45.1",
    "psycopg[binary]",
]
